services:

  agent1:
    image: arangodb/arangodb:3.11.11
    container_name: agent1
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication false
              --agency.my-address tcp://agent1:8529
              --agency.endpoint tcp://agent1:8529
              --server.endpoint tcp://0.0.0.0:8529
              --agency.activate true
              --agency.size 3
              --agency.supervision true
              --database.directory agency'

  agent2:
    image: arangodb/arangodb:3.11.11
    container_name: agent2
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication false
              --agency.my-address tcp://agent2:8529
              --agency.endpoint tcp://agent1:8529
              --server.endpoint tcp://0.0.0.0:8529
              --agency.activate true
              --agency.size 3
              --agency.supervision true
              --database.directory agency'
    depends_on:
      - agent1

  agent3:
    image: arangodb/arangodb:3.11.11
    container_name: agent3
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication false
              --agency.my-address tcp://agent3:8529
              --agency.endpoint tcp://agent1:8529
              --server.endpoint tcp://0.0.0.0:8529
              --agency.activate true
              --agency.size 3
              --agency.supervision true
              --database.directory agency'
    depends_on:
      - agent1

  db1:
    image: arangodb/arangodb:3.11.11
    container_name: db1
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication=false
              --server.endpoint tcp://0.0.0.0:8529
              --cluster.my-address tcp://db1:8529
              --cluster.my-role DBSERVER
              --cluster.agency-endpoint tcp://agent1:8529
              --cluster.agency-endpoint tcp://agent2:8529
              --cluster.agency-endpoint tcp://agent3:8529
              --database.directory db'
    depends_on:
      - agent1
      - agent2
      - agent3

  db2:
    image: arangodb/arangodb:3.11.11
    container_name: db2
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication=false
              --server.endpoint tcp://0.0.0.0:8529
              --cluster.my-address tcp://db2:8529
              --cluster.my-role DBSERVER
              --cluster.agency-endpoint tcp://agent1:8529
              --cluster.agency-endpoint tcp://agent2:8529
              --cluster.agency-endpoint tcp://agent3:8529
              --database.directory db'
    depends_on:
      - agent1
      - agent2
      - agent3

  db3:
    image: arangodb/arangodb:3.11.11
    container_name: db3
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication=false
              --server.endpoint tcp://0.0.0.0:8529
              --cluster.my-address tcp://db3:8529
              --cluster.my-role DBSERVER
              --cluster.agency-endpoint tcp://agent1:8529
              --cluster.agency-endpoint tcp://agent2:8529
              --cluster.agency-endpoint tcp://agent3:8529
              --database.directory db'
    depends_on:
      - agent1
      - agent2
      - agent3

  coordinator1:
    image: arangodb/arangodb:3.11.11
    container_name: coordinator1
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication=false
              --server.endpoint tcp://0.0.0.0:8529
              --cluster.my-address tcp://coordinator1:8529
              --cluster.my-role COORDINATOR
              --cluster.agency-endpoint tcp://agent1:8529
              --cluster.agency-endpoint tcp://agent2:8529
              --cluster.agency-endpoint tcp://agent3:8529
              --database.directory coordinator'
    ports:
      - '8529:8529'
    depends_on:
      - db1
      - db2
      - db3

  coordinator2:
    image: arangodb/arangodb:3.11.11
    container_name: coordinator2
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication=false
              --server.endpoint tcp://0.0.0.0:8529
              --cluster.my-address tcp://coordinator2:8529
              --cluster.my-role COORDINATOR
              --cluster.agency-endpoint tcp://agent1:8529
              --cluster.agency-endpoint tcp://agent2:8529
              --cluster.agency-endpoint tcp://agent3:8529
              --database.directory coordinator'
    ports:
      - '8530:8529'
    depends_on:
      - db1
      - db2
      - db3

  coordinator3:
    image: arangodb/arangodb:3.11.11
    container_name: coordinator3
    environment:
      ARANGO_NO_AUTH: 1
    command: 'arangod --server.authentication=false
              --server.endpoint tcp://0.0.0.0:8529
              --cluster.my-address tcp://coordinator3:8529
              --cluster.my-role COORDINATOR
              --cluster.agency-endpoint tcp://agent1:8529
              --cluster.agency-endpoint tcp://agent2:8529
              --cluster.agency-endpoint tcp://agent3:8529
              --database.directory coordinator'
    ports:
      - '8531:8529'
    depends_on:
      - db1
      - db2
      - db3
